sudo: false
language: python
python:
  - '3.6'
  - 3.7-dev
install: make
script:
  - make lint
  - make coverage
  - codecov
cache: pip
matrix:
  include:
    - python: '3.6'
    - python: 3.7-dev
  allow_failures:
    - python: 3.7-dev